---

- name: Create configuration directory
  ansible.builtin.file:
    path: /etc/sysfs.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy basic configuration file
  ansible.builtin.copy:
    src: sysfs.conf
    dest: /etc/sysfs.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart sysfs

- name: Setup autostart for RedHat only
  when: ansible_facts.os_family == 'RedHat'
  block:

    - name: Setup symlink /etc/init.d -> /etc/rc.d/init.d
      ansible.builtin.file:
        src: /etc/rc.d/init.d
        dest: /etc/init.d
        state: link
      become: yes

    - name: Copy startup script
      ansible.builtin.copy:
        src: sysfsutils
        dest: /etc/rc.d/init.d/sysfsutils
        owner: root
        group: root
        mode: "0755"
      notify: Restart sysfs

    - name: Copy init functions
      ansible.builtin.copy:
        src: init-functions
        dest: /etc/rc.d/init.d/init-functions
        owner: root
        group: root
        mode: "0644"
      notify: Restart sysfs

- name: Distribute drop-in files from files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/sysfs.d/{{ item | basename }}
    owner: root
    group: root
    mode: "0644"
  notify: Restart sysfs
  loop: "{{ sysfs_dropin_files | default([]) }}"

- name: Distribute drop-in files from template
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/sysfs.d/{{ item | basename | regex_replace('\.j2') }}
    owner: root
    group: root
    mode: "0644"
  notify: Restart sysfs
  loop: "{{ sysfs_dropin_templates | default([]) }}"

# - name: Create systemd service
#   ansible.builtin.template:
#     src: templates/sysfsutils.service.j2
#     dest: /etc/systemd/system/sysfsutils.service
#     mode: "0644"
#   notify: Restart sysfs

- name: Start daemon
  ansible.builtin.systemd:
    name: "{{ sysfs_daemon }}"
    enabled: true
    daemon_reload: true
