---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    sysfs_dropin_files: ['scheduler']
  tasks:
    - name: Include role 'ansible-role-sysfs'
      ansible.builtin.include_role:
        name: ansible-role-sysfs
